language: go
go:
- '1.10'

sudo: required

install:
- echo "install"
- go get -u "github.com/astaxie/beego"
- go get -u "github.com/bitly/go-simplejson"

script:
- echo "script"

before_install:
- openssl aes-256-cbc -K $encrypted_bae4eee6b0f8_key -iv $encrypted_bae4eee6b0f8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- ssh travis@139.199.166.124 -o StrictHostKeyChecking=no "cd ~/server/server && go version && bee version"

addons:
  ssh_known_hosts: 139.199.166.124
