language: go
go:
- 1.1
sudo: required
install:
- echo "install"
script:
- echo "script"
before_install:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- openssl aes-256-cbc -K $encrypted_bae4eee6b0f8_key -iv $encrypted_bae4eee6b0f8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- ssh ubuntu@139.199.166.124 "cd ~/server/server && pwd"
addons:
  ssh_known_hosts: 139.199.166.124
